"use client";

import { FileWarning, X, AlertTriangle, ShieldCheck } from "lucide-react";

interface IncidentReportProps {
  isVisible: boolean;
  onClose: () => void;
}

export default function IncidentReport({ isVisible, onClose }: IncidentReportProps) {
  if (!isVisible) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
      <div 
        className="w-full max-w-2xl bg-white rounded-2xl shadow-2xl flex flex-col overflow-hidden border border-gray-200"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-gray-100 bg-red-50">
          <div className="flex items-center gap-3">
            <FileWarning className="w-5 h-5 text-red-600" />
            <h2 className="text-base font-bold font-sans text-red-600 tracking-wide">INCIDENT REPORT #XF-902</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-full hover:bg-red-100 transition-colors text-red-400 hover:text-red-600">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 md:p-8 space-y-6">
          <div className="flex items-center gap-4 p-5 rounded-xl border border-red-100 bg-red-50/50">
            <div className="p-3 bg-red-100 rounded-full">
              <AlertTriangle className="w-6 h-6 text-red-600 flex-shrink-0" />
            </div>
            <div>
              <h3 className="font-bold text-gray-900 text-lg">Flash Loan Attack Prevented</h3>
              <p className="text-sm text-gray-500 mt-1 font-medium">The Swarm successfully identified and blocked a malicious transaction before it could drain the contract.</p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <ReportItem label="Threat Type" value="Flash Loan / Reentrancy" valueClass="text-red-600" />
            <ReportItem label="Risk Level" value="CRITICAL" valueClass="text-red-600 font-black" />
            <ReportItem label="Confidence Score" value="99.9%" valueClass="text-gray-900" />
            <ReportItem label="Exploit Verified" value="YES (Sandbox)" valueClass="text-gray-700" />
          </div>

          <div className="p-5 bg-gray-50 border border-gray-100 rounded-xl">
            <p className="text-[10px] uppercase font-bold text-gray-400 mb-3 tracking-wider">Automated Actions Taken:</p>
            <ul className="space-y-3 text-sm font-medium">
              <li className="flex items-center gap-3 text-gray-700">
                <ShieldCheck className="w-5 h-5 text-green-500" /> 
                Sandbox Fork Created & Exploit Replayed
              </li>
              <li className="flex items-center gap-3 text-gray-700">
                <ShieldCheck className="w-5 h-5 text-green-500" /> 
                Emergency Pause Triggered on Mainnet
              </li>
              <li className="flex items-center gap-3 text-gray-700">
                <ShieldCheck className="w-5 h-5 text-green-500" /> 
                $12.4M USD Protected from Drain
              </li>
            </ul>
          </div>

          <div className="pt-2">
            <p className="text-[10px] uppercase font-bold text-gray-400 mb-2 tracking-wider">Recommended Action</p>
            <p className="text-sm text-gray-600 font-medium">Review the verified exploit trace in the sandbox environment. Apply the generated patch (Patch #492) and undergo MultiSig review before unpausing.</p>
          </div>
        </div>
        
        {/* Footer */}
        <div className="px-8 py-5 border-t border-gray-100 bg-gray-50 flex justify-between items-center text-xs font-mono font-medium text-gray-400">
          <span>Generated by: Remediation Agent</span>
          <span>{new Date().toISOString().split('T')[0]}</span>
        </div>
      </div>
    </div>
  );
}

function ReportItem({ label, value, valueClass }: { label: string, value: string, valueClass: string }) {
  return (
    <div className="p-4 bg-white border border-gray-100 rounded-xl shadow-sm">
      <p className="text-[10px] uppercase font-bold text-gray-400 mb-1.5 tracking-wider">{label}</p>
      <p className={`font-mono font-semibold text-sm ${valueClass}`}>{value}</p>
    </div>
  );
}
